### ISSUE TITLE
Improve card swiping UX

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/swipeforfuture.com#31]
~1. I'm thinking about ways to prevent cards from being swiped until the card stack drop animation has completed (new cards are rendered in the middle of the screen). This would prevent buggy behaviors when swiping rapidly before cards are ready. Ideally, we could `disable` the swipe gesture handler when cards are returning to the middle of the screen.~

2. When the game ends, we should be able to disable card swiping while the timeout before shoring endgame state is executed. If the endgame would trigger a timeout to complete the swiping animation, while also fading the screen to (transparent) black or red, and also disabling the swiping handlers of the next card - this would be a much better endgame UX. This kind of control should probably be added to `Deck` to allow that component to disable `Card`s it controls.

*Edit: the following was resolved in #35*

~3. Right now, the only thing required to`trigger` a swipe is to move the cursor/finger fast enough. Could we improve the UX by limiting the swipes to only happen after the card has been moved a certain distance? Either with or without the `trigger` happening by swiping fast enough.~

**Comment by Muthaias** [comment]
I've spent some time looking into the implementation and as far as I can see the state handling is broken.

There are a number of things with both 'useSprings` and `useGesture` that don't play well with the current set up when updating props.

I think it would be wise and take a step back make sure the hooks are utilized correctly. (Or find another library which better supports our use case.)

**Comment by Muthaias** [comment]
But in reality these are two completely different issues. I'll create another issue regarding the state of the cards and state/prop problems. I'll try to fix it during the day.

**Comment by Muthaias** [comment]
This is a great point!

If I remember correctly. Tinder has both buttons and swipe functionality in order to control the selection process. I like having both since swiping is not optimal in all cases. (Also maybe adding buttons could improve accessibility)

On your number idea 2: I think we could either add visual activation `zones` in the background or we could tint the cards when they reach an activated distance from the center.

On your idea number 1: What do you think about having only one card being interactive at a time? I think we could improve the state by completely removing the interactivity for the cards which are not currently active.

**Comment by Greenheart** [comment]
This is outdated. CLosing.
