### ISSUE TITLE
Card or event as entry point to game

### ISSUE THREAD

**Issue by Muthaias** [Greenheart/swipeforfuture.com#64]
It would be nice if one could use a specific card as the entry point to the game. This could improve the possibility to design the user experience.

* Possibly by reference to an event card?
* Should and event specify whether or not it is an initial event? (This allows multiple random entry points based on probability)

**Comment by Greenheart** [comment]
The idea of using events to create a controlled storyline as entry to the game is a good idea.

Using multiple possible entry points adds complexity, but adds replayability since we can let players get thrown into multiple different starting conditions. "You never get to choose the state of the world when you're elected president", right!?

**Comment by Greenheart** [comment]
After discussion tonight, we concluded this issue to be resolved by the current implementation:
* We can trigger a specific event on start by using a flag in `defaultState` to trigger an event with 100% probability.
* This will show the first event card, which works basically like a normal card.
